name: Discord Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, closed, reopened]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Push
        if: github.event_name == 'push'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 Novo Commit - SCUM Server Manager"
          description: "**Commit:** ${{ github.event.head_commit.message }}\n**Autor:** ${{ github.event.head_commit.author.name }}\n**Branch:** ${{ github.ref_name }}"
          color: "0x00ff00"
      
      - name: Notify Discord on Pull Request
        if: github.event_name == 'pull_request'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🔀 Pull Request - SCUM Server Manager"
          description: "**PR:** ${{ github.event.pull_request.title }}\n**Autor:** ${{ github.event.pull_request.user.login }}\n**Status:** ${{ github.event.action }}"
          color: "0x0099ff"
      
      - name: Notify Discord on Issue
        if: github.event_name == 'issues'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🐛 Issue - SCUM Server Manager"
          description: "**Issue:** ${{ github.event.issue.title }}\n**Autor:** ${{ github.event.issue.user.login }}\n**Status:** ${{ github.event.action }}"
          color: "0xff9900"
      
      - name: Notify Discord on Release
        if: github.event_name == 'release'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🎉 Novo Release - SCUM Server Manager"
          description: "**Release:** ${{ github.event.release.name }}\n**Tag:** ${{ github.event.release.tag_name }}\n**Descrição:** ${{ github.event.release.body }}"
          color: "0xff00ff"
