import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en-US';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  'pt-BR': {
    // Navigation
    'dashboard': 'PAINEL',
    'players': 'JOGADORES',
    'fama': 'FAMA',
    'discord': 'DISCORD',
    'administration': 'ADMINISTRAÇÃO',
    'vehicles': 'VEÍCULOS',
    'settings': 'CONFIGURAÇÕES',
    'backups': 'BACKUPS',
    'analytics': 'ANALÍTICAS',
    
    // Status
    'online': 'ONLINE',
    'offline': 'OFFLINE',
    'loading': 'CARREGANDO...',
    'error': 'ERRO',
    'success': 'SUCESSO',
    'warning': 'AVISO',
    
    // Actions
    'save': 'SALVAR',
    'cancel': 'CANCELAR',
    'edit': 'EDITAR',
    'delete': 'EXCLUIR',
    'refresh': 'ATUALIZAR',
    'test': 'TESTAR',
    'start': 'INICIAR',
    'stop': 'PARAR',
    'restart': 'REINICIAR',
    'logout': 'SAIR',
    'saving': 'Salvando...',
    'reload': 'Recarregar',
    'save_settings': 'Salvar Configurações',
    
    // Server
    'server_status': 'STATUS DO SERVIDOR',
    'server_online': 'SERVIDOR ONLINE',
    'server_offline': 'SERVIDOR OFFLINE',
    'players_online': 'JOGADORES ONLINE',
    'max_players': 'MÁXIMO DE JOGADORES',
    'uptime': 'TEMPO ATIVO',
    'restart_count': 'CONTAGEM DE REINÍCIAS',
    
    // Settings
    'server_config': 'CONFIGURAÇÃO DO SERVIDOR',
    'discord_bot': 'BOT DO DISCORD',
    'scheduled_restart': 'REINÍCIO PROGRAMADO',
    'database': 'BANCO DE DADOS',
    
    // Bot Discord
    'bot_enabled': 'Bot do Discord',
    'bot_disabled': 'Bot do Discord',
    'bot_token': 'Token do Bot',
    'guild_id': 'ID do Servidor',
    'webhook_key': 'Chave do Webhook',
    
    // Channels
    'vehicle_channel': 'Canal de Veículos',
    'mount_channel': 'Canal de Montagem',
    'denunciation_channel': 'Canal de Denúncias',
    
    // Commands
    'vehicle_registration': 'Registro de Veículos (/rv)',
    'mount_registration': 'Registro de Montagem (/rm)',
    'mount_complete': 'Montagem Completa (/mc)',
    'vehicle_denunciation': 'Denúncia de Veículos (/dv)',
    
    // Command Settings
    'enabled': 'Ativado',
    'disabled': 'Desativado',
    'cooldown_seconds': 'Cooldown (segundos)',
    'embed_color': 'Cor do Embed',
    'required_roles': 'Cargos Necessários (separados por vírgula)',
    'command_prefix': 'Prefixo do Comando',
    
    // Linking
    'user_linking': 'Vinculação de Usuários',
    'linking_system': 'Sistema de Vinculação',
    'expiration_hours': 'Expiração (horas)',
    'max_linked_users': 'Máximo de Usuários',
    
    // Messages
    'loading_system': 'CARREGANDO SISTEMA...',
    'save_success': 'Configurações salvas com sucesso',
    'save_error': 'Erro ao salvar configurações',
    'test_success': 'Teste concluído com sucesso',
    
    // Language
    'select_language': 'Selecionar Idioma',
    'test_error': 'Erro ao realizar teste',
    
    // Information
    'information': 'Informação',
    'click_sections': 'Clique nas seções para expandir/recolher',
    'auto_save': 'As configurações são salvas automaticamente',
    'restart_required': 'Algumas alterações podem exigir reinicialização',
    
    // Placeholders
    'bot_token_placeholder': 'Token do bot do Discord',
    'guild_id_placeholder': 'ID do servidor Discord',
    'channel_id_placeholder': 'ID do Canal',
    'roles_placeholder': 'Staff, Adm, Moderador',
    
    // Time
    'last_update': 'Última atualização',
    'next_update': 'Próxima atualização',
    'update_in': 'Atualizações em',
    
    // Bunkers
    'bunker_status': 'Status dos Bunkers',
    'active_bunkers': 'Bunkers Ativos',
    'blocked_bunkers': 'Bunkers Bloqueados',
    'bunker_coordinates': 'Coordenadas',
    'activation_time': 'Tempo de Ativação',
    'activation_method': 'Método de Ativação',
    
    // Fame
    'fame_points': 'Pontos de Fama',
    'top_players': 'Melhores Jogadores',
    'total_fame': 'Fama Total',
    'fame_percentage': 'Porcentagem',
    
    // Vehicles
    'vehicle_events': 'Eventos de Veículos',
    'vehicle_destroyed': 'Destruído',
    'vehicle_disappeared': 'Desaparecido',
    'vehicle_inactive_timer': 'Temporizador de veículo inativo atingido',
    
    // Admin
    'admin_log': 'Log de Administração',
    'admin_actions': 'Ações de Administração',
    'admin_commands': 'Comandos de Administração',
    
    // Chat
    'chat_messages': 'Mensagens do Chat',
    'chat_in_game': 'Chat no Jogo',
    'chat_type': 'Tipo de Chat',
    'chat_message': 'Mensagem',
    
    // Webhooks
    'webhook_config': 'Configuração do Webhook',
    'webhook_url': 'URL do Webhook',
    'webhook_test': 'Testar Webhook',
    'webhook_save': 'Salvar Webhook',
    
    // General
    'name': 'Nome',
    'status': 'Status',
    'date': 'Data',
    'time': 'Hora',
    'action': 'Ação',
    'details': 'Detalhes',
    'description': 'Descrição',
    'type': 'Tipo',
    'value': 'Valor',
    'count': 'Contagem',
    'total': 'Total',
    'average': 'Média',
    'minimum': 'Mínimo',
    'maximum': 'Máximo',
    'none': 'Nenhum',
    'all': 'Todos',
    'yes': 'Sim',
    'no': 'Não',
    'true': 'Verdadeiro',
    'false': 'Falso',
    'unknown': 'Desconhecido',
    'pending': 'Pendente',
    'completed': 'Concluído',
    'cancelled': 'Cancelado',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'verified': 'Verificado',
    'rejected': 'Rejeitado',
    'support_project': 'APOIAR PROJETO',
    'system_status': 'STATUS DO SISTEMA',
    'system_settings': 'CONFIGURAÇÕES DO SISTEMA',
    'survival_control_system': 'Sistema de Controle de Sobrevivência',
    'server': 'SERVIDOR',
    'next_auto_update': 'Próxima atualização automática',
    'next_bunker_check': 'Próxima verificação de bunker',
    'starting': 'Iniciando...',
    'stopping': 'Parando...',
    'restarting': 'Reiniciando...',
    'start_server': 'Iniciar Servidor',
    
    // Manual Updates
    'manual_updates': 'Atualizações Manuais',
    'click_to_update': 'Clique para atualizar',
    'updated_successfully': 'Atualizado com sucesso',
    'update_error': 'Erro ao atualizar',
    'manual_update_info': 'O backend executa automaticamente, mas você pode forçar atualizações manuais quando necessário.',
    'stop_server': 'Parar Servidor',
    'restart_server': 'Reiniciar Servidor',
    'updating': 'Atualizando...',
    'auto': 'Automático',
    'manual': 'Manual',
    'next_reset': 'Próximo Reset',
    'error_loading_bunkers': 'Erro ao carregar status dos bunkers',
    'loading_bunkers': 'Carregando bunkers...',
    'no_data_available': 'Nenhum dado disponível',
    'no_active_bunkers': 'Nenhum bunker ativo',
    'bunker': 'bunker',
    'blocked': 'Bloqueado',
    'loading_top3': 'Carregando top 3...',
    'error_loading_data': 'Erro ao carregar dados',
    'try_again': 'Tentar novamente',
    'top3_fame': 'TOP 3 FAMA',
    'no_players_found': 'Nenhum jogador encontrado',
    'error_loading_fame': 'Erro ao carregar dados de fama',
    'playtime': 'Tempo de Jogo',
    'last_login': 'Último Login',
    'tags': 'Tags',
    'filter_name': 'Filtrar nome',
    'filter_steamid': 'Filtrar SteamID',
    'all_tags': 'Todas as tags',
    'date_time': 'Data/Hora',
    'command': 'Comando',
    'parameter_message': 'Parâmetro/Mensagem',
    'filter_command': 'Filtrar comando',
    'filter_parameter_message': 'Filtrar parâmetro/mensagem',
    'no_events_found': 'Nenhum evento encontrado',
    'destroyed': 'Destruído',
    'disappeared': 'Desaparecido',
    'vehicle_inactive_timer_reached': 'Temporizador de veículo inativo atingido',
    'event': 'Evento',
    'owner': 'Proprietário',
    'vehicle_id': 'ID do Veículo',
    'location': 'Localização',
    'filter_owner': 'Filtrar proprietário',
    'no_owner': 'Sem Proprietário',
    'online_players_statistics': 'Jogadores Online & Estatísticas',
    'view_all_players_status_playtime_ranking': 'Visualizar todos os jogadores, status, tempo de jogo e ranking',
    'fame_system': 'Sistema de Fama',
    'manage_player_reputation_fame_system': 'Gerenciar a reputação do jogador e sistema de fama',
    'discord_settings': 'Configurações do Discord',
    'manage_discord_webhooks_notifications': 'Gerenciar webhooks do Discord para notificações',
    'manage_administrative_functions_scum_server': 'Gerenciar funções administrativas do servidor SCUM',
    'vehicle_history_events': 'Histórico de Veículos & Eventos',
    'view_all_vehicle_events_processed_system': 'Visualizar todos os eventos de veículos processados pelo sistema',
    'manage_advanced_scum_server_settings': 'Gerenciar configurações avançadas do servidor SCUM',
    'manage_server_configuration_settings': 'Gerenciar configurações do servidor SCUM',
    'fullscreen_enter': 'Entrar em Fullscreen',
    'fullscreen_exit': 'Sair do Fullscreen',
    'loading_admin_log': 'Carregando log de administração...',
    'loading_fame_data': 'Carregando dados de fama...',
    'search_player': 'Buscar jogador...',
    'all_players': 'Todos os jogadores',
    'top3': 'Top 3',
    'top5': 'Top 5',
    'top10': 'Top 10',
    'all_levels': 'Todos os níveis',
    'high_fame': 'Alta fama',
    'medium_fame': 'Média fama',
    'low_fame': 'Baixa fama',
    'update': 'Atualizar',
    'fame_ranking': 'Ranking de Fama',
    'activate': 'Ativar',
    'chat_in_game_disabled': 'Chat In Game desativado',
    'recent_message': 'mensagem recente',
    'no_chat_messages': 'Nenhuma mensagem do chat in game.',
    'loading_settings': 'Carregando configurações...',
    'system_active': 'Sistema Ativo',
    'system_inactive': 'Sistema Inativo',
    'configured_times': 'Horários Configurados',
    'no_time_configured': 'Nenhum horário configurado',
    'add_time': 'Adicionar Horário',
    'adding': 'Adicionando...',
    'add': 'Adicionar',
    'automatic_restart_system': 'Sistema de Restart Automático',
    'activates_deactivates_scheduled_restart_system': 'Ativa/desativa o sistema de restart programado',
    'deactivate': 'Desativar',
    'hide_steam_ids': 'Ocultar Steam IDs',
    'hides_steam_ids_all_sections_videos_screenshots': 'Oculta Steam IDs em todas as seções para vídeos e screenshots',
    'hide_steam_ids_for_videos': 'OCULTAR STEAM IDs (Para vídeos)',
    'loading_server_settings': 'Carregando configurações do servidor...',
    'server_settings': 'Configurações do Servidor',
    'server_configuration': 'Configuração do Servidor',
    'server_port': 'Porta do Servidor',
    'use_battleye': 'Usar BattlEye',
    'activates_deactivates_discord_bot': 'Ativa/desativa o bot do Discord',
    'discord_server_id': 'ID do Servidor Discord',
    'discord_channels': 'Canais do Discord',
    'discord_commands': 'Comandos do Discord',
    'change_to_english': 'Mudar para Inglês',
    'change_to_portuguese': 'Change to Portuguese',
    'general_settings': 'Configurações Gerais',
    'basic_server_settings': 'Configurações básicas do servidor',
    'server_name': 'Nome do Servidor',
    'server_description': 'Descrição do Servidor',
    'server_password': 'Senha do Servidor',
    'server_banner_url': 'URL do Banner do Servidor',
    'server_playstyle': 'Estilo de Jogo',
    'welcome_message': 'Mensagem de Boas-vindas',
    'message_of_the_day': 'Mensagem do Dia',
    'motd_cooldown': 'Cooldown da Mensagem do Dia',
    'min_server_tickrate': 'Tick Rate Mínimo',
    'max_server_tickrate': 'Tick Rate Máximo',
    'max_ping': 'Ping Máximo',
    'logout_timer': 'Timer de Logout',
    'logout_timer_captured': 'Timer de Logout Capturado',
    'logout_timer_bunker': 'Timer de Logout no Bunker',
    'allow_first_person': 'Permitir Primeira Pessoa',
    'allow_third_person': 'Permitir Terceira Pessoa',
    'allow_crosshair': 'Permitir Mira',
    'allow_voting': 'Permitir Votação',
    'allow_map_screen': 'Permitir Mapa',
    'allow_kill_claiming': 'Permitir Reivindicação de Kill',
    'allow_coma': 'Permitir Coma',
    'allow_mines_and_traps': 'Permitir Minas e Armadilhas',
    'allow_skill_gain_safe_zones': 'Ganho de Habilidade em Zonas Seguras',
    'allow_events': 'Permitir Eventos',
    'limit_global_chat': 'Limitar Chat Global',
    'allow_global_chat': 'Permitir Chat Global',
    'allow_local_chat': 'Permitir Chat Local',
    'allow_squad_chat': 'Permitir Chat de Squad',
    'allow_admin_chat': 'Permitir Chat de Admin',
    'rusty_locks_logging': 'Log de Fechaduras Enferrujadas',
    'hide_kill_notification': 'Ocultar Notificação de Kill',
    'disable_timed_gifts': 'Desabilitar Presentes Temporizados',
    'map_base_building_restriction': 'Restrição de Construção no Mapa',
    'disable_base_building': 'Desabilitar Construção de Base',
    'voting_duration': 'Duração da Votação',
    'player_minimal_voting_interest': 'Interesse Mínimo de Votação',
    'player_positive_vote_percentage': 'Porcentagem de Voto Positivo',
    'master_server_endpoints': 'Endpoints do Master Server',
    'master_server_update_send_interval': 'Intervalo de Atualização do Master Server',
    'partial_wipe': 'Wipe Parcial',
    'gold_wipe': 'Wipe de Ouro',
    'full_wipe': 'Wipe Completo',
    'item_virtualization_relevancy_update_period': 'Período de Atualização de Relevância',
    'item_virtualization_event_processing_time_budget': 'Orçamento de Tempo de Processamento',
    'item_virtualization_visitor_distance_travelled_for_update': 'Distância Percorrida para Atualização',
    'item_virtualization_visitor_bounds': 'Limites do Visitante',
    'virtualized_item_bounds': 'Limites de Item Virtualizado',
    'fame_gain_multiplier': 'Multiplicador de Fama',
    'fame_point_penalty_on_death': 'Penalidade de Fama na Morte',
    'fame_point_penalty_on_killed': 'Penalidade de Fama ao Ser Morto',
    'fame_point_reward_on_kill': 'Recompensa de Fama por Kill',
    'log_suicides': 'Log de Suicídios',
    'enable_spawn_on_ground': 'Spawn no Chão',
    'delete_inactive_users': 'Deletar Usuários Inativos',
    'days_since_last_login_to_become_inactive': 'Dias para Usuário Inativo',
    'delete_banned_users': 'Deletar Usuários Banidos',
    'maximum_time_for_chests_in_forbidden_zones': 'Tempo Máximo para Baús',
    'log_chest_ownership': 'Log de Propriedade de Baús',
    'settings_version': 'Versão das Configurações',
    'master_server_is_local_test': 'Master Server é Teste Local',
    // Seções adicionais e toggles
    'world_settings': 'Configurações do Mundo',
    'world_settings_desc': 'NPCs, animais e ambiente',
    'vehicle_settings': 'Configurações de Veículos',
    'vehicle_settings_desc': 'Veículos e combustível',
    'damage_settings': 'Configurações de Dano',
    'damage_settings_desc': 'Multiplicadores de dano',
    'respawn_settings': 'Configurações de Respawn',
    'respawn_settings_desc': 'Preços e tempos de respawn',
    'special_resources': 'Recursos Especiais',
    'special_resources_desc': 'Recursos e opções especiais do servidor',
    'value_settings': 'Configurações de Valores',
    'toggle_settings': 'Configurações de Toggle',
    'searching_for': 'Pesquisando por',
    // Respawn e Recursos Especiais (pt-BR)
    'respawn_price': 'Preço de Respawn',
    'respawn_time': 'Tempo de Respawn',
    'special_option': 'Opção Especial',
    'enable_feature': 'Habilitar Recurso',
    'disable_feature': 'Desabilitar Recurso',
    'resource_limit': 'Limite de Recurso',
    // Traduções para Configurações do Mundo (pt-BR)
    'max_allowed_birds': 'Máximo de Pássaros',
    'max_allowed_npcs': 'Máximo de NPCs',
    'max_allowed_characters': 'Máximo de Personagens',
    'max_allowed_puppets': 'Máximo de Puppets',
    'max_allowed_animals': 'Máximo de Animais',
    'encounter_base_character_amount_multiplier': 'Multiplicador Base de NPCs',
    'encounter_extra_character_per_player_multiplier': 'Multiplicador Extra por Jogador',
    'encounter_extra_character_player_cap_multiplier': 'Multiplicador Limite por Jogador',
    'encounter_character_respawn_time_multiplier': 'Multiplicador de Tempo de Respawn de NPC',
    'encounter_character_respawn_batch_size_multiplier': 'Multiplicador de Tamanho de Lote de Respawn',
    'encounter_character_aggressive_spawn_chance_override': 'Chance Override de Spawn Agressivo',
    'encounter_character_ai_noise_response_radius_multiplier': 'Multiplicador de Raio de Resposta IA',
    'encounter_horde_group_base_character_amount_multiplier': 'Multiplicador Base de Grupo de Horda',
    'encounter_horde_group_extra_character_per_player_multiplier': 'Multiplicador Extra de Grupo de Horda por Jogador',
    'encounter_horde_group_extra_character_player_cap_multiplier': 'Multiplicador Limite de Grupo de Horda por Jogador',
    'encounter_horde_base_character_amount_multiplier': 'Multiplicador Base de Horda',
    'encounter_horde_extra_character_per_player_multiplier': 'Multiplicador Extra de Horda por Jogador',
    'encounter_horde_extra_character_player_cap_multiplier': 'Multiplicador Limite de Horda por Jogador',
    'encounter_horde_activation_chance_multiplier': 'Multiplicador de Chance de Ativação de Horda',
    'encounter_horde_noise_check_cooldown_multiplier': 'Multiplicador de Cooldown de Verificação de Ruído de Horda',
    'encounter_horde_spawn_distance_multiplier': 'Multiplicador de Distância de Spawn de Horda',
    'puppet_world_encounter_spawn_weight_multiplier': 'Multiplicador de Peso de Spawn de Puppet',
    'animal_world_encounter_spawn_weight_multiplier': 'Multiplicador de Peso de Spawn de Animal',
    'dropship_world_encounter_spawn_weight_multiplier': 'Multiplicador de Peso de Spawn de Dropship',
    'dropship_abandoned_bunker_encounter_trigger_chance': 'Chance de Trigger de Encontro de Dropship em Bunker Abandonado',
    'base_building_encounter_trigger_chance': 'Chance de Trigger de Encontro em Construção de Base',
    'base_building_encounter_trigger_time_multiplier': 'Multiplicador de Tempo de Trigger de Encontro em Construção de Base',
    'base_building_encounter_min_num_elements_to_start': 'Mínimo de Elementos para Iniciar Encontro em Base',
    'base_building_encounter_min_num_elements_to_end': 'Mínimo de Elementos para Terminar Encontro em Base',
    'base_building_encounter_damage_percentage_increase_per_squad_member': 'Aumento de Dano (%) por Membro do Squad',
    'base_building_encounter_time_to_full_min_num_to_end': 'Tempo para Cheio (mínimo para terminar)',
    'base_building_encounter_maximum_min_to_end_reduction': 'Redução Máxima do Mínimo para Terminar',
    'max_allowed_drones': 'Máximo de Drones',
    'abandoned_bunker_commotion_threshold': 'Limite de Agitação em Bunker Abandonado',
    'abandoned_bunker_commotion_threshold_per_player_extra': 'Limite de Agitação Extra por Jogador em Bunker Abandonado',
    'abandoned_bunker_enemy_activation_threshold': 'Limite de Ativação de Inimigo em Bunker Abandonado',
    'abandoned_bunker_enemy_activation_threshold_per_player_extra': 'Limite de Ativação de Inimigo Extra por Jogador em Bunker Abandonado',
    'puppet_health_multiplier': 'Multiplicador de Vida de Puppet',
    'dropship_health_multiplier': 'Multiplicador de Vida de Dropship',
    'sentry_health_multiplier': 'Multiplicador de Vida de Sentry',
    'base_building_attacker_sentry_health_multiplier': 'Multiplicador de Vida de Sentry Atacante de Base',
    'armed_npc_difficulty_level': 'Nível de Dificuldade de NPC Armado',
    'probability_for_armed_npc_to_drop_item_from_hands_when_searched': 'Probabilidade de NPC Armado Dropar Item das Mãos ao Ser Revistado',
    'nighttime_darkness': 'Escuridão Noturna',
    'start_time_of_day': 'Horário de Início do Dia',
    'sunrise_time': 'Horário do Nascer do Sol',
    'sunset_time': 'Horário do Pôr do Sol',
    'time_of_day_speed': 'Velocidade do Tempo do Dia',
    'weather_rain_frequency_multiplier': 'Multiplicador de Frequência de Chuva',
    // Veículos (pt-BR)
    'fuel_drain_from_engine_multiplier': 'Consumo de Combustível',
    'battery_drain_from_engine_multiplier': 'Consumo de Bateria',
    'battery_drain_from_devices_multiplier': 'Consumo de Bateria por Dispositivos',
    'battery_drain_from_inactivity_multiplier': 'Consumo de Bateria por Inatividade',
    'battery_charge_with_alternator_multiplier': 'Carga de Bateria com Alternador',
    'battery_charge_with_dynamo_multiplier': 'Carga de Bateria com Dínamo',
    'kinglet_duster_max_amount': 'Máximo Kinglet Duster',
    'kinglet_duster_max_functional_amount': 'Máximo Funcional Kinglet Duster',
    'kinglet_duster_min_purchased_amount': 'Mínimo Comprado Kinglet Duster',
    'dirtbike_max_amount': 'Máximo Dirtbike',
    'dirtbike_max_functional_amount': 'Máximo Funcional Dirtbike',
    'dirtbike_min_purchased_amount': 'Mínimo Comprado Dirtbike',
    'laika_max_amount': 'Máximo Laika',
    'laika_max_functional_amount': 'Máximo Funcional Laika',
    'laika_min_purchased_amount': 'Mínimo Comprado Laika',
    'motorboat_max_amount': 'Máximo Motorboat',
    'motorboat_max_functional_amount': 'Máximo Funcional Motorboat',
    'motorboat_min_purchased_amount': 'Mínimo Comprado Motorboat',
    'wheelbarrow_max_amount': 'Máximo Wheelbarrow',
    'wheelbarrow_max_functional_amount': 'Máximo Funcional Wheelbarrow',
    'wheelbarrow_min_purchased_amount': 'Mínimo Comprado Wheelbarrow',
    'wolfswagen_max_amount': 'Máximo Wolfswagen',
    'wolfswagen_max_functional_amount': 'Máximo Funcional Wolfswagen',
    'wolfswagen_min_purchased_amount': 'Mínimo Comprado Wolfswagen',
    'bicycle_max_amount': 'Máximo Bicycle',
    'bicycle_max_functional_amount': 'Máximo Funcional Bicycle',
    'bicycle_min_purchased_amount': 'Mínimo Comprado Bicycle',
    'rager_max_amount': 'Máximo Rager',
    'rager_max_functional_amount': 'Máximo Funcional Rager',
    'rager_min_purchased_amount': 'Mínimo Comprado Rager',
    'cruiser_max_amount': 'Máximo Cruiser',
    'cruiser_max_functional_amount': 'Máximo Funcional Cruiser',
    'cruiser_min_purchased_amount': 'Mínimo Comprado Cruiser',
    'ris_max_amount': 'Máximo Ris',
    'ris_max_functional_amount': 'Máximo Funcional Ris',
    'ris_min_purchased_amount': 'Mínimo Comprado Ris',
    'sup_max_amount': 'Máximo SUP',
    'sup_max_functional_amount': 'Máximo Funcional SUP',
    'sup_min_purchased_amount': 'Mínimo Comprado SUP',
    'kinglet_mariner_max_amount': 'Máximo Kinglet Mariner',
    'kinglet_mariner_max_functional_amount': 'Máximo Funcional Kinglet Mariner',
    'kinglet_mariner_min_purchased_amount': 'Mínimo Comprado Kinglet Mariner',
    'tractor_max_amount': 'Máximo Tractor',
    'tractor_max_functional_amount': 'Máximo Funcional Tractor',
    'tractor_min_purchased_amount': 'Mínimo Comprado Tractor',
    'maximum_time_of_vehicle_inactivity': 'Tempo Máximo de Inatividade do Veículo',
    'maximum_time_for_vehicles_in_forbidden_zones': 'Tempo Máximo em Zonas Proibidas',
    'log_vehicle_destroyed': 'Log de Veículos Destruídos',
    'enable_vehicle_damage': 'Habilitar Dano a Veículos',
    'vehicle_decay_time': 'Tempo de Decaimento do Veículo',
    'human_to_vehicle_damage_multiplier': 'Multiplicador de Dano Humano vs Veículo',
    'zombie_to_vehicle_damage_multiplier': 'Multiplicador de Dano Zumbi vs Veículo',
    // Dano (pt-BR)
    'human_to_human_damage_multiplier': 'Dano Jogador vs Jogador',
    'human_to_human_armed_melee_damage_multiplier': 'Dano Armado Corpo a Corpo',
    'human_to_human_unarmed_melee_damage_multiplier': 'Dano Desarmado Corpo a Corpo',
    'human_to_human_throwing_damage_multiplier': 'Dano de Arremesso',
    'show_kill_feed': 'Mostrar Feed de Kills',
    'sentry_damage_multiplier': 'Dano de Sentry',
    'sentry_railgun_damage_multiplier': 'Dano de Railgun Sentry',
    'sentry_grenade_damage_multiplier': 'Dano de Granada Sentry',
    'base_building_attacker_sentry_damage_multiplier': 'Dano Sentry Atacante Base',
    'base_building_attacker_sentry_railgun_damage_multiplier': 'Dano Railgun Sentry Atacante',
    'base_building_attacker_sentry_grenade_damage_multiplier': 'Dano Granada Sentry Atacante',
    'sentry_base_building_damage_multiplier': 'Dano Sentry vs Base',
    'dropship_damage_multiplier': 'Dano de Dropship',
    'dropship_railgun_damage_multiplier': 'Dano Railgun Dropship',
    'dropship_base_building_elements_damage_multiplier': 'Dano Dropship vs Elementos Base',
    'zombie_damage_multiplier': 'Dano de Zumbis',
    'item_decay_damage_multiplier': 'Decaimento de Itens',
    'food_decay_damage_multiplier': 'Decaimento de Comida',
    'weapon_decay_damage_on_firing': 'Decaimento de Armas',
    'lock_protection_damage_multiplier': 'Proteção de Fechaduras',
    // Respawn (pt-BR)
    'allow_sector_respawn': 'Permitir Respawn por Setor',
    'allow_shelter_respawn': 'Permitir Respawn por Abrigo',
    'allow_squadmate_respawn': 'Permitir Respawn por Squad',
    'random_respawn_price': 'Preço Respawn Aleatório',
    'sector_respawn_price': 'Preço Respawn Setor',
    'shelter_respawn_price': 'Preço Respawn Abrigo',
    'squad_respawn_price': 'Preço Respawn Squad',
    'random_respawn_initial_time': 'Tempo Inicial Aleatório',
    'sector_respawn_initial_time': 'Tempo Inicial Setor',
    'shelter_respawn_initial_time': 'Tempo Inicial Abrigo',
    'squad_respawn_initial_time': 'Tempo Inicial Squad',
    'random_respawn_cooldown': 'Cooldown Aleatório',
    'sector_respawn_cooldown': 'Cooldown Setor',
    'shelter_respawn_cooldown': 'Cooldown Abrigo',
    'squad_respawn_cooldown': 'Cooldown Squad',
    'random_cooldown_reset_multiplier': 'Multiplicador Reset Aleatório',
    'sector_cooldown_reset_multiplier': 'Multiplicador Reset Setor',
    'shelter_cooldown_reset_multiplier': 'Multiplicador Reset Abrigo',
    'squad_cooldown_reset_multiplier': 'Multiplicador Reset Squad',
    'random_price_per_squadmate_modifier': 'Modificador Preço Aleatório',
    'sector_price_per_squadmate_modifier': 'Modificador Preço Setor',
    'shelter_price_per_squadmate_modifier': 'Modificador Preço Abrigo',
    'commit_suicide_initial_time': 'Tempo Inicial Suicídio',
    'commit_suicide_cooldown': 'Cooldown Suicídio',
    'commit_suicide_cooldown_reset_multiplier': 'Multiplicador Reset Suicídio',
    'maximum_base_proximity_when_spawning': 'Proximidade Máxima da Base',
    'permadeath_threshold': 'Limite de Morte Permanente',
    // Recursos Especiais (pt-BR)
    'flag_overtake_duration': 'Duração Tomada de Bandeira',
    'maximum_amount_of_elements_per_flag': 'Máximo Elementos por Bandeira',
    'extra_elements_per_flag_for_additional_squad_member': 'Elementos Extra por Membro Squad',
    'maximum_number_of_expanded_elements_per_flag': 'Máximo Elementos Expandidos por Bandeira',
    'allow_multiple_flags_per_player': 'Permitir Múltiplas Bandeiras por Jogador',
    'allow_flag_placement_on_bb_elements': 'Permitir Colocação de Bandeira em Elementos BB',
    'chest_acquisition_duration': 'Duração Aquisição de Baú',
    'weapon_rack_max_amount_per_flag_area': 'Máximo Suporte de Armas por Área de Bandeira',
    'weapon_rack_start_decaying_if_flag_area_has_more_than': 'Suporte de Armas Decai se Área Tem Mais Que',
    'wall_weapon_rack_max_amount_per_flag_area': 'Máximo Suporte de Armas na Parede por Área',
    'wall_weapon_rack_start_decaying_if_flag_area_has_more_than': 'Suporte de Armas na Parede Decai se Área Tem Mais Que',
    'well_max_amount_per_flag_area': 'Máximo Poços por Área de Bandeira',
    'well_start_decaying_if_flag_area_has_more_than': 'Poços Decaem se Área Tem Mais Que',
    'turret_max_amount_per_flag_area': 'Máximo Torres por Área de Bandeira',
    'turret_start_decaying_if_flag_area_has_more_than': 'Torres Decaem se Área Tem Mais Que',
    'garden_max_amount_per_flag_area': 'Máximo Jardins por Área de Bandeira',
    'allow_floor_placement_on_half_and_low_walls': 'Permitir Colocação de Piso em Paredes Baixas',
    'allow_wall_placement_on_half_and_low_walls': 'Permitir Colocação de Parede em Paredes Baixas',
    'raid_protection_type': 'Tipo de Proteção de Raid',
    'raid_protection_enable_log': 'Habilitar Log de Proteção de Raid',
    'raid_protection_flag_specific_change_setting_cooldown': 'Cooldown Mudança Configuração Específica Bandeira',
    'raid_protection_flag_specific_change_setting_price': 'Preço Mudança Configuração Específica Bandeira',
    'raid_protection_flag_specific_max_protection_time': 'Tempo Máximo Proteção Específica Bandeira',
    'raid_protection_offline_protection_start_delay': 'Atraso Início Proteção Offline',
    'raid_protection_offline_max_protection_time': 'Tempo Máximo Proteção Offline',
    'raid_protection_global_should_show_raid_times_message': 'Mostrar Mensagem Horários de Raid',
    'raid_protection_global_should_show_raid_announcement_message': 'Mostrar Mensagem Anúncio de Raid',
    'raid_protection_global_should_show_raid_start_end_messages': 'Mostrar Mensagens Início/Fim de Raid',
    'water_price_per_unit_multiplier': 'Multiplicador Preço Água por Unidade',
    'water_periodic_initial_amount_multiplier': 'Multiplicador Quantidade Inicial Periódica Água',
    'water_periodic_max_amount_multiplier': 'Multiplicador Quantidade Máxima Periódica Água',
    'water_periodic_replenish_amount_multiplier': 'Multiplicador Quantidade Reabastecimento Periódico Água',
    'water_periodic_replenish_interval_multiplier': 'Multiplicador Intervalo Reabastecimento Periódico Água',
    'water_proximity_replenish_amount_multiplier': 'Multiplicador Quantidade Reabastecimento Proximidade Água',
    'water_proximity_replenish_chance_multiplier': 'Multiplicador Chance Reabastecimento Proximidade Água',
    'water_proximity_replenish_timeout_multiplier': 'Multiplicador Timeout Reabastecimento Proximidade Água',
    'gasoline_price_per_unit_multiplier': 'Multiplicador Preço Gasolina por Unidade',
    'gasoline_periodic_initial_amount_multiplier': 'Multiplicador Quantidade Inicial Periódica Gasolina',
    'gasoline_periodic_max_amount_multiplier': 'Multiplicador Quantidade Máxima Periódica Gasolina',
    'gasoline_periodic_replenish_amount_multiplier': 'Multiplicador Quantidade Reabastecimento Periódico Gasolina',
    'gasoline_periodic_replenish_interval_multiplier': 'Multiplicador Intervalo Reabastecimento Periódico Gasolina',
    'gasoline_proximity_replenish_amount_multiplier': 'Multiplicador Quantidade Reabastecimento Proximidade Gasolina',
    'gasoline_proximity_replenish_chance_multiplier': 'Multiplicador Chance Reabastecimento Proximidade Gasolina',
    'gasoline_proximity_replenish_timeout_multiplier': 'Multiplicador Timeout Reabastecimento Proximidade Gasolina',
    'custom_map_enabled': 'Mapa Customizado Habilitado',
    'door_lockability.garage': 'Trancabilidade de Portas de Garagem',
    'encounter_never_respawn_characters': 'Encontros Nunca Respawnam Personagens',
    'abandoned_bunker_reset_armory_lockers_on_activation_only': 'Reset Armários do Arsenal Apenas na Ativação'
  },
  'en-US': {
    // Navigation
    'dashboard': 'DASHBOARD',
    'players': 'PLAYERS',
    'fama': 'FAME',
    'discord': 'DISCORD',
    'administration': 'ADMINISTRATION',
    'vehicles': 'VEHICLES',
    'settings': 'SETTINGS',
    'backups': 'BACKUPS',
    'analytics': 'ANALYTICS',
    
    // Status
    'online': 'ONLINE',
    'offline': 'OFFLINE',
    'loading': 'LOADING...',
    'error': 'ERROR',
    'success': 'SUCCESS',
    'warning': 'WARNING',
    
    // Actions
    'save': 'SAVE',
    'cancel': 'CANCEL',
    'edit': 'EDIT',
    'delete': 'DELETE',
    'refresh': 'REFRESH',
    'test': 'TEST',
    'start': 'START',
    'stop': 'STOP',
    'restart': 'RESTART',
    'logout': 'LOGOUT',
    'saving': 'Saving...',
    'reload': 'Reload',
    'save_settings': 'Save Settings',
    
    // Server
    'server_status': 'SERVER STATUS',
    'server_online': 'SERVER ONLINE',
    'server_offline': 'SERVER OFFLINE',
    'players_online': 'PLAYERS ONLINE',
    'uptime': 'UPTIME',
    'restart_count': 'RESTART COUNT',
    
    // Settings
    'server_config': 'SERVER CONFIGURATION',
    'discord_bot': 'DISCORD BOT',
    'scheduled_restart': 'SCHEDULED RESTART',
    'database': 'DATABASE',
    
    // Bot Discord
    'bot_enabled': 'Discord Bot',
    'bot_disabled': 'Discord Bot',
    'guild_id': 'Guild ID',
    'webhook_key': 'Webhook Key',
    
    // Channels
    'vehicle_channel': 'Vehicle Channel',
    'mount_channel': 'Mount Channel',
    'denunciation_channel': 'Denunciation Channel',
    
    // Commands
    'vehicle_registration': 'Vehicle Registration (/rv)',
    'mount_registration': 'Mount Registration (/rm)',
    'mount_complete': 'Mount Complete (/mc)',
    'vehicle_denunciation': 'Vehicle Denunciation (/dv)',
    
    // Command Settings
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'cooldown_seconds': 'Cooldown (seconds)',
    'embed_color': 'Embed Color',
    'required_roles': 'Required Roles (comma separated)',
    'command_prefix': 'Command Prefix',
    
    // Linking
    'user_linking': 'User Linking',
    'linking_system': 'Linking System',
    'expiration_hours': 'Expiration (hours)',
    'max_linked_users': 'Max Linked Users',
    
    // Messages
    'loading_system': 'LOADING SYSTEM...',
    'save_success': 'Settings saved successfully',
    'save_error': 'Error saving settings',
    'test_success': 'Test completed successfully',
    'test_error': 'Error performing test',
    
    // Information
    'information': 'Information',
    'click_sections': 'Click sections to expand/collapse',
    'auto_save': 'Settings are saved automatically',
    'restart_required': 'Some changes may require restart',
    
    // Placeholders
    'bot_token_placeholder': 'Discord bot token',
    'guild_id_placeholder': 'Discord server ID',
    'channel_id_placeholder': 'Channel ID',
    'roles_placeholder': 'Staff, Adm, Moderator',
    
    // Time
    'last_update': 'Last update',
    'next_update': 'Next update',
    'update_in': 'Updates in',
    
    // Bunkers
    'bunker_status': 'Bunker Status',
    'active_bunkers': 'Active Bunkers',
    'blocked_bunkers': 'Blocked Bunkers',
    'bunker_coordinates': 'Coordinates',
    'activation_time': 'Activation Time',
    'activation_method': 'Activation Method',
    
    // Fame
    'fame_points': 'Fame Points',
    'top_players': 'Top Players',
    'total_fame': 'Total Fame',
    'fame_percentage': 'Percentage',
    
    // Vehicles
    'vehicle_events': 'Vehicle Events',
    'vehicle_destroyed': 'Destroyed',
    'vehicle_disappeared': 'Disappeared',
    'vehicle_inactive_timer': 'Vehicle inactive timer reached',
    
    // Admin
    'admin_log': 'Admin Log',
    'admin_actions': 'Admin Actions',
    'admin_commands': 'Admin Commands',
    
    // Chat
    'chat_messages': 'Chat Messages',
    'chat_type': 'Chat Type',
    'chat_message': 'Message',
    
    // Webhooks
    'webhook_config': 'Webhook Configuration',
    'webhook_url': 'Webhook URL',
    'webhook_test': 'Test Webhook',
    'webhook_save': 'Save Webhook',
    
    // General
    'name': 'Name',
    'status': 'Status',
    'date': 'Date',
    'time': 'Time',
    'action': 'Action',
    'details': 'Details',
    'description': 'Description',
    'type': 'Type',
    'value': 'Value',
    'count': 'Count',
    'total': 'Total',
    'average': 'Average',
    'minimum': 'Minimum',
    'maximum': 'Maximum',
    'none': 'None',
    'all': 'All',
    'yes': 'Yes',
    'no': 'No',
    'true': 'True',
    'false': 'False',
    'unknown': 'Unknown',
    'pending': 'Pending',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'active': 'Active',
    'inactive': 'Inactive',
    'verified': 'Verified',
    'rejected': 'Rejected',
    'support_project': 'SUPPORT PROJECT',
    'system_status': 'SYSTEM STATUS',
    'system_settings': 'SYSTEM SETTINGS',
    'survival_control_system': 'Survival Control System',
    'server': 'SERVER',
    'next_auto_update': 'Next automatic update',
    'next_bunker_check': 'Next bunker check',
    'starting': 'Starting...',
    'stopping': 'Stopping...',
    'restarting': 'Restarting...',
    'start_server': 'Start Server',
    'stop_server': 'Stop Server',
    'restart_server': 'Restart Server',
    'updating': 'Updating...',
    'auto': 'Auto',
    'manual': 'Manual',
    'next_reset': 'Next Reset',
    'error_loading_bunkers': 'Error loading bunker status',
    'loading_bunkers': 'Loading bunkers...',
    'no_data_available': 'No data available',
    'no_active_bunkers': 'No active bunkers',
    'bunker': 'bunker',
    'blocked': 'Blocked',
    'loading_top3': 'Loading top 3...',
    'error_loading_data': 'Error loading data',
    'try_again': 'Try again',
    'top3_fame': 'TOP 3 FAME',
    'no_players_found': 'No players found',
    'error_loading_fame': 'Error loading fame data',
    'playtime': 'Playtime',
    'last_login': 'Last Login',
    'tags': 'Tags',
    'filter_name': 'Filter name',
    'filter_steamid': 'Filter SteamID',
    'all_tags': 'All tags',
    'date_time': 'Date/Time',
    'command': 'Command',
    'parameter_message': 'Parameter/Message',
    'filter_command': 'Filter command',
    'filter_parameter_message': 'Filter parameter/message',
    'no_events_found': 'No events found',
    'destroyed': 'Destroyed',
    'disappeared': 'Disappeared',
    'vehicle_inactive_timer_reached': 'Vehicle inactive timer reached',
    'event': 'Event',
    'owner': 'Owner',
    'vehicle_id': 'Vehicle ID',
    'location': 'Location',
    'filter_owner': 'Filter owner',
    'no_owner': 'No Owner',
    'online_players_statistics': 'Online Players & Statistics',
    'view_all_players_status_playtime_ranking': 'View all players, status, playtime and ranking',
    'fame_system': 'Fame System',
    'manage_player_reputation_fame_system': 'Manage the player reputation and fame system',
    'discord_settings': 'Discord Settings',
    'manage_discord_webhooks_notifications': 'Manage Discord webhooks for notifications',
    'manage_administrative_functions_scum_server': 'Manage administrative functions of the SCUM server',
    'vehicle_history_events': 'Vehicle History & Events',
    'view_all_vehicle_events_processed_system': 'View all vehicle events processed by the system',
    'manage_advanced_scum_server_settings': 'Manage advanced SCUM server settings',
    'manage_server_configuration_settings': 'Manage SCUM server configuration settings',
    'fullscreen_enter': 'Enter Fullscreen',
    'fullscreen_exit': 'Exit Fullscreen',
    'loading_admin_log': 'Loading admin log...',
    'loading_fame_data': 'Loading fame data...',
    'search_player': 'Search player...',
    'all_players': 'All players',
    'top3': 'Top 3',
    'top5': 'Top 5',
    'top10': 'Top 10',
    'all_levels': 'All levels',
    'high_fame': 'High fame',
    'medium_fame': 'Medium fame',
    'low_fame': 'Low fame',
    'update': 'Update',
    'fame_ranking': 'Fame Ranking',
    'activate': 'Activate',
    'chat_in_game': 'Chat In Game',
    'chat_in_game_disabled': 'Chat In Game disabled',
    'recent_message': 'recent message',
    'no_chat_messages': 'No chat messages.',
    'loading_settings': 'Loading settings...',
    'system_active': 'System Active',
    'system_inactive': 'System Inactive',
    'configured_times': 'Configured Times',
    'no_time_configured': 'No time configured',
    'add_time': 'Add Time',
    'adding': 'Adding...',
    'add': 'Add',
    'automatic_restart_system': 'Automatic Restart System',
    'activates_deactivates_scheduled_restart_system': 'Activates/deactivates the scheduled restart system',
    'deactivate': 'Deactivate',
    'hide_steam_ids': 'Hide Steam IDs',
    'hides_steam_ids_all_sections_videos_screenshots': 'Hides Steam IDs in all sections for videos and screenshots',
    'hide_steam_ids_for_videos': 'HIDE STEAM IDs (For videos)',
    'loading_server_settings': 'Loading server settings...',
    'server_settings': 'Server Settings',
    'server_configuration': 'Server Configuration',
    'server_port': 'Server Port',
    'max_players': 'Max Players',
    'use_battleye': 'Use BattlEye',
    'activates_deactivates_discord_bot': 'Activates/deactivates the Discord bot',
    'bot_token': 'Bot Token',
    'discord_server_id': 'Discord Server ID',
    'discord_channels': 'Discord Channels',
    'discord_commands': 'Discord Commands',
    'change_to_english': 'Change to English',
    'change_to_portuguese': 'Change to Portuguese',
    'select_language': 'Select Language',
    'general_settings': 'General Settings',
    'basic_server_settings': 'Basic server settings',
    'server_name': 'Server Name',
    'server_description': 'Server Description',
    'server_password': 'Server Password',
    'server_banner_url': 'Server Banner URL',
    'server_playstyle': 'Server Playstyle',
    'welcome_message': 'Welcome Message',
    'message_of_the_day': 'Message of the Day',
    'motd_cooldown': 'MOTD Cooldown',
    'min_server_tickrate': 'Min Server Tickrate',
    'max_server_tickrate': 'Max Server Tickrate',
    'max_ping': 'Max Ping',
    'logout_timer': 'Logout Timer',
    'logout_timer_captured': 'Logout Timer Captured',
    'logout_timer_bunker': 'Logout Timer in Bunker',
    'allow_first_person': 'Allow First Person',
    'allow_third_person': 'Allow Third Person',
    'allow_crosshair': 'Allow Crosshair',
    'allow_voting': 'Allow Voting',
    'allow_map_screen': 'Allow Map Screen',
    'allow_kill_claiming': 'Allow Kill Claiming',
    'allow_coma': 'Allow Coma',
    'allow_mines_and_traps': 'Allow Mines and Traps',
    'allow_skill_gain_safe_zones': 'Skill Gain in Safe Zones',
    'allow_events': 'Allow Events',
    'limit_global_chat': 'Limit Global Chat',
    'allow_global_chat': 'Allow Global Chat',
    'allow_local_chat': 'Allow Local Chat',
    'allow_squad_chat': 'Allow Squad Chat',
    'allow_admin_chat': 'Allow Admin Chat',
    'rusty_locks_logging': 'Rusty Locks Logging',
    'hide_kill_notification': 'Hide Kill Notification',
    'disable_timed_gifts': 'Disable Timed Gifts',
    'map_base_building_restriction': 'Map Base Building Restriction',
    'disable_base_building': 'Disable Base Building',
    'voting_duration': 'Voting Duration',
    'player_minimal_voting_interest': 'Player Minimal Voting Interest',
    'player_positive_vote_percentage': 'Player Positive Vote Percentage',
    'master_server_endpoints': 'Master Server Endpoints',
    'master_server_update_send_interval': 'Master Server Update Send Interval',
    'partial_wipe': 'Partial Wipe',
    'gold_wipe': 'Gold Wipe',
    
    // Manual Updates
    'manual_updates': 'Manual Updates',
    'click_to_update': 'Click to update',
    'updated_successfully': 'Updated successfully',
    'update_error': 'Error updating',
    'manual_update_info': 'The backend runs automatically, but you can force manual updates when needed.',
    'full_wipe': 'Full Wipe',
    'item_virtualization_relevancy_update_period': 'Item Virtualization Relevancy Update Period',
    'item_virtualization_event_processing_time_budget': 'Item Virtualization Event Processing Time Budget',
    'item_virtualization_visitor_distance_travelled_for_update': 'Item Virtualization Visitor Distance Travelled For Update',
    'item_virtualization_visitor_bounds': 'Item Virtualization Visitor Bounds',
    'virtualized_item_bounds': 'Virtualized Item Bounds',
    'fame_gain_multiplier': 'Fame Gain Multiplier',
    'fame_point_penalty_on_death': 'Fame Point Penalty On Death',
    'fame_point_penalty_on_killed': 'Fame Point Penalty On Killed',
    'fame_point_reward_on_kill': 'Fame Point Reward On Kill',
    'log_suicides': 'Log Suicides',
    'enable_spawn_on_ground': 'Enable Spawn On Ground',
    'delete_inactive_users': 'Delete Inactive Users',
    'days_since_last_login_to_become_inactive': 'Days Since Last Login To Become Inactive',
    'delete_banned_users': 'Delete Banned Users',
    'maximum_time_for_chests_in_forbidden_zones': 'Maximum Time For Chests In Forbidden Zones',
    'log_chest_ownership': 'Log Chest Ownership',
    'settings_version': 'Settings Version',
    'master_server_is_local_test': 'Master Server Is Local Test',
    // Seções adicionais e toggles
    'world_settings': 'World Settings',
    'world_settings_desc': 'NPCs, animals and environment',
    'vehicle_settings': 'Vehicle Settings',
    'vehicle_settings_desc': 'Vehicles and fuel',
    'damage_settings': 'Damage Settings',
    'damage_settings_desc': 'Damage multipliers',
    'respawn_settings': 'Respawn Settings',
    'respawn_settings_desc': 'Respawn prices and times',
    'special_resources': 'Special Resources',
    'special_resources_desc': 'Special server resources and options',
    'value_settings': 'Value Settings',
    'toggle_settings': 'Toggle Settings',
    'searching_for': 'Searching for',
    // Respawn e Recursos Especiais (en-US)
    'respawn_price': 'Respawn Price',
    'respawn_time': 'Respawn Time',
    'special_option': 'Special Option',
    'enable_feature': 'Enable Feature',
    'disable_feature': 'Disable Feature',
    'resource_limit': 'Resource Limit',
    // Traduções para Configurações do Mundo (en-US)
    'max_allowed_birds': 'Max Allowed Birds',
    'max_allowed_npcs': 'Max Allowed NPCs',
    'max_allowed_characters': 'Max Allowed Characters',
    'max_allowed_puppets': 'Max Allowed Puppets',
    'max_allowed_animals': 'Max Allowed Animals',
    'encounter_base_character_amount_multiplier': 'Base Character Amount Multiplier',
    'encounter_extra_character_per_player_multiplier': 'Extra Character Per Player Multiplier',
    'encounter_extra_character_player_cap_multiplier': 'Extra Character Player Cap Multiplier',
    'encounter_character_respawn_time_multiplier': 'Character Respawn Time Multiplier',
    'encounter_character_respawn_batch_size_multiplier': 'Character Respawn Batch Size Multiplier',
    'encounter_character_aggressive_spawn_chance_override': 'Aggressive Spawn Chance Override',
    'encounter_character_ai_noise_response_radius_multiplier': 'AI Noise Response Radius Multiplier',
    'encounter_horde_group_base_character_amount_multiplier': 'Horde Group Base Character Amount Multiplier',
    'encounter_horde_group_extra_character_per_player_multiplier': 'Horde Group Extra Character Per Player Multiplier',
    'encounter_horde_group_extra_character_player_cap_multiplier': 'Horde Group Extra Character Player Cap Multiplier',
    'encounter_horde_base_character_amount_multiplier': 'Horde Base Character Amount Multiplier',
    'encounter_horde_extra_character_per_player_multiplier': 'Horde Extra Character Per Player Multiplier',
    'encounter_horde_extra_character_player_cap_multiplier': 'Horde Extra Character Player Cap Multiplier',
    'encounter_horde_activation_chance_multiplier': 'Horde Activation Chance Multiplier',
    'encounter_horde_noise_check_cooldown_multiplier': 'Horde Noise Check Cooldown Multiplier',
    'encounter_horde_spawn_distance_multiplier': 'Horde Spawn Distance Multiplier',
    'puppet_world_encounter_spawn_weight_multiplier': 'Puppet World Encounter Spawn Weight Multiplier',
    'animal_world_encounter_spawn_weight_multiplier': 'Animal World Encounter Spawn Weight Multiplier',
    'dropship_world_encounter_spawn_weight_multiplier': 'Dropship World Encounter Spawn Weight Multiplier',
    'dropship_abandoned_bunker_encounter_trigger_chance': 'Dropship Abandoned Bunker Encounter Trigger Chance',
    'base_building_encounter_trigger_chance': 'Base Building Encounter Trigger Chance',
    'base_building_encounter_trigger_time_multiplier': 'Base Building Encounter Trigger Time Multiplier',
    'base_building_encounter_min_num_elements_to_start': 'Base Building Encounter Min Num Elements To Start',
    'base_building_encounter_min_num_elements_to_end': 'Base Building Encounter Min Num Elements To End',
    'base_building_encounter_damage_percentage_increase_per_squad_member': 'Base Building Encounter Damage % Increase Per Squad Member',
    'base_building_encounter_time_to_full_min_num_to_end': 'Base Building Encounter Time To Full Min Num To End',
    'base_building_encounter_maximum_min_to_end_reduction': 'Base Building Encounter Maximum Min To End Reduction',
    'max_allowed_drones': 'Max Allowed Drones',
    'abandoned_bunker_commotion_threshold': 'Abandoned Bunker Commotion Threshold',
    'abandoned_bunker_commotion_threshold_per_player_extra': 'Abandoned Bunker Commotion Threshold Per Player Extra',
    'abandoned_bunker_enemy_activation_threshold': 'Abandoned Bunker Enemy Activation Threshold',
    'abandoned_bunker_enemy_activation_threshold_per_player_extra': 'Abandoned Bunker Enemy Activation Threshold Per Player Extra',
    'puppet_health_multiplier': 'Puppet Health Multiplier',
    'dropship_health_multiplier': 'Dropship Health Multiplier',
    'sentry_health_multiplier': 'Sentry Health Multiplier',
    'base_building_attacker_sentry_health_multiplier': 'Base Building Attacker Sentry Health Multiplier',
    'armed_npc_difficulty_level': 'Armed NPC Difficulty Level',
    'probability_for_armed_npc_to_drop_item_from_hands_when_searched': 'Probability For Armed NPC To Drop Item From Hands When Searched',
    'nighttime_darkness': 'Nighttime Darkness',
    'start_time_of_day': 'Start Time Of Day',
    'sunrise_time': 'Sunrise Time',
    'sunset_time': 'Sunset Time',
    'time_of_day_speed': 'Time Of Day Speed',
    'weather_rain_frequency_multiplier': 'Rain Frequency Multiplier',
    // Veículos (en-US)
    'fuel_drain_from_engine_multiplier': 'Fuel Drain From Engine Multiplier',
    'battery_drain_from_engine_multiplier': 'Battery Drain From Engine Multiplier',
    'battery_drain_from_devices_multiplier': 'Battery Drain From Devices Multiplier',
    'battery_drain_from_inactivity_multiplier': 'Battery Drain From Inactivity Multiplier',
    'battery_charge_with_alternator_multiplier': 'Battery Charge With Alternator Multiplier',
    'battery_charge_with_dynamo_multiplier': 'Battery Charge With Dynamo Multiplier',
    'kinglet_duster_max_amount': 'Kinglet Duster Max Amount',
    'kinglet_duster_max_functional_amount': 'Kinglet Duster Max Functional Amount',
    'kinglet_duster_min_purchased_amount': 'Kinglet Duster Min Purchased Amount',
    'dirtbike_max_amount': 'Dirtbike Max Amount',
    'dirtbike_max_functional_amount': 'Dirtbike Max Functional Amount',
    'dirtbike_min_purchased_amount': 'Dirtbike Min Purchased Amount',
    'laika_max_amount': 'Laika Max Amount',
    'laika_max_functional_amount': 'Laika Max Functional Amount',
    'laika_min_purchased_amount': 'Laika Min Purchased Amount',
    'motorboat_max_amount': 'Motorboat Max Amount',
    'motorboat_max_functional_amount': 'Motorboat Max Functional Amount',
    'motorboat_min_purchased_amount': 'Motorboat Min Purchased Amount',
    'wheelbarrow_max_amount': 'Wheelbarrow Max Amount',
    'wheelbarrow_max_functional_amount': 'Wheelbarrow Max Functional Amount',
    'wheelbarrow_min_purchased_amount': 'Wheelbarrow Min Purchased Amount',
    'wolfswagen_max_amount': 'Wolfswagen Max Amount',
    'wolfswagen_max_functional_amount': 'Wolfswagen Max Functional Amount',
    'wolfswagen_min_purchased_amount': 'Wolfswagen Min Purchased Amount',
    'bicycle_max_amount': 'Bicycle Max Amount',
    'bicycle_max_functional_amount': 'Bicycle Max Functional Amount',
    'bicycle_min_purchased_amount': 'Bicycle Min Purchased Amount',
    'rager_max_amount': 'Rager Max Amount',
    'rager_max_functional_amount': 'Rager Max Functional Amount',
    'rager_min_purchased_amount': 'Rager Min Purchased Amount',
    'cruiser_max_amount': 'Cruiser Max Amount',
    'cruiser_max_functional_amount': 'Cruiser Max Functional Amount',
    'cruiser_min_purchased_amount': 'Cruiser Min Purchased Amount',
    'ris_max_amount': 'Ris Max Amount',
    'ris_max_functional_amount': 'Ris Max Functional Amount',
    'ris_min_purchased_amount': 'Ris Min Purchased Amount',
    'sup_max_amount': 'SUP Max Amount',
    'sup_max_functional_amount': 'SUP Max Functional Amount',
    'sup_min_purchased_amount': 'SUP Min Purchased Amount',
    'kinglet_mariner_max_amount': 'Kinglet Mariner Max Amount',
    'kinglet_mariner_max_functional_amount': 'Kinglet Mariner Max Functional Amount',
    'kinglet_mariner_min_purchased_amount': 'Kinglet Mariner Min Purchased Amount',
    'tractor_max_amount': 'Tractor Max Amount',
    'tractor_max_functional_amount': 'Tractor Max Functional Amount',
    'tractor_min_purchased_amount': 'Tractor Min Purchased Amount',
    'maximum_time_of_vehicle_inactivity': 'Maximum Time Of Vehicle Inactivity',
    'maximum_time_for_vehicles_in_forbidden_zones': 'Maximum Time For Vehicles In Forbidden Zones',
    'log_vehicle_destroyed': 'Log Vehicle Destroyed',
    'enable_vehicle_damage': 'Enable Vehicle Damage',
    'vehicle_decay_time': 'Vehicle Decay Time',
    'human_to_vehicle_damage_multiplier': 'Human To Vehicle Damage Multiplier',
    'zombie_to_vehicle_damage_multiplier': 'Zombie To Vehicle Damage Multiplier',
    // Dano (en-US)
    'human_to_human_damage_multiplier': 'Human To Human Damage Multiplier',
    'human_to_human_armed_melee_damage_multiplier': 'Human To Human Armed Melee Damage Multiplier',
    'human_to_human_unarmed_melee_damage_multiplier': 'Human To Human Unarmed Melee Damage Multiplier',
    'human_to_human_throwing_damage_multiplier': 'Human To Human Throwing Damage Multiplier',
    'show_kill_feed': 'Show Kill Feed',
    'sentry_damage_multiplier': 'Sentry Damage Multiplier',
    'sentry_railgun_damage_multiplier': 'Sentry Railgun Damage Multiplier',
    'sentry_grenade_damage_multiplier': 'Sentry Grenade Damage Multiplier',
    'base_building_attacker_sentry_damage_multiplier': 'Base Building Attacker Sentry Damage Multiplier',
    'base_building_attacker_sentry_railgun_damage_multiplier': 'Base Building Attacker Sentry Railgun Damage Multiplier',
    'base_building_attacker_sentry_grenade_damage_multiplier': 'Base Building Attacker Sentry Grenade Damage Multiplier',
    'sentry_base_building_damage_multiplier': 'Sentry Base Building Damage Multiplier',
    'dropship_damage_multiplier': 'Dropship Damage Multiplier',
    'dropship_railgun_damage_multiplier': 'Dropship Railgun Damage Multiplier',
    'dropship_base_building_elements_damage_multiplier': 'Dropship Base Building Elements Damage Multiplier',
    'zombie_damage_multiplier': 'Zombie Damage Multiplier',
    'item_decay_damage_multiplier': 'Item Decay Damage Multiplier',
    'food_decay_damage_multiplier': 'Food Decay Damage Multiplier',
    'weapon_decay_damage_on_firing': 'Weapon Decay Damage On Firing',
    'lock_protection_damage_multiplier': 'Lock Protection Damage Multiplier',
    // Respawn (en-US)
    'allow_sector_respawn': 'Allow Sector Respawn',
    'allow_shelter_respawn': 'Allow Shelter Respawn',
    'allow_squadmate_respawn': 'Allow Squadmate Respawn',
    'random_respawn_price': 'Random Respawn Price',
    'sector_respawn_price': 'Sector Respawn Price',
    'shelter_respawn_price': 'Shelter Respawn Price',
    'squad_respawn_price': 'Squad Respawn Price',
    'random_respawn_initial_time': 'Random Respawn Initial Time',
    'sector_respawn_initial_time': 'Sector Respawn Initial Time',
    'shelter_respawn_initial_time': 'Shelter Respawn Initial Time',
    'squad_respawn_initial_time': 'Squad Respawn Initial Time',
    'random_respawn_cooldown': 'Random Respawn Cooldown',
    'sector_respawn_cooldown': 'Sector Respawn Cooldown',
    'shelter_respawn_cooldown': 'Shelter Respawn Cooldown',
    'squad_respawn_cooldown': 'Squad Respawn Cooldown',
    'random_cooldown_reset_multiplier': 'Random Cooldown Reset Multiplier',
    'sector_cooldown_reset_multiplier': 'Sector Cooldown Reset Multiplier',
    'shelter_cooldown_reset_multiplier': 'Shelter Cooldown Reset Multiplier',
    'squad_cooldown_reset_multiplier': 'Squad Cooldown Reset Multiplier',
    'random_price_per_squadmate_modifier': 'Random Price Per Squadmate Modifier',
    'sector_price_per_squadmate_modifier': 'Sector Price Per Squadmate Modifier',
    'shelter_price_per_squadmate_modifier': 'Shelter Price Per Squadmate Modifier',
    'commit_suicide_initial_time': 'Commit Suicide Initial Time',
    'commit_suicide_cooldown': 'Commit Suicide Cooldown',
    'commit_suicide_cooldown_reset_multiplier': 'Commit Suicide Cooldown Reset Multiplier',
    'maximum_base_proximity_when_spawning': 'Maximum Base Proximity When Spawning',
    'permadeath_threshold': 'Permadeath Threshold',
    // Recursos Especiais (en-US)
    'flag_overtake_duration': 'Flag Overtake Duration',
    'maximum_amount_of_elements_per_flag': 'Maximum Amount Of Elements Per Flag',
    'extra_elements_per_flag_for_additional_squad_member': 'Extra Elements Per Flag For Additional Squad Member',
    'maximum_number_of_expanded_elements_per_flag': 'Maximum Number Of Expanded Elements Per Flag',
    'allow_multiple_flags_per_player': 'Allow Multiple Flags Per Player',
    'allow_flag_placement_on_bb_elements': 'Allow Flag Placement On BB Elements',
    'chest_acquisition_duration': 'Chest Acquisition Duration',
    'weapon_rack_max_amount_per_flag_area': 'Weapon Rack Max Amount Per Flag Area',
    'weapon_rack_start_decaying_if_flag_area_has_more_than': 'Weapon Rack Start Decaying If Flag Area Has More Than',
    'wall_weapon_rack_max_amount_per_flag_area': 'Wall Weapon Rack Max Amount Per Flag Area',
    'wall_weapon_rack_start_decaying_if_flag_area_has_more_than': 'Wall Weapon Rack Start Decaying If Flag Area Has More Than',
    'well_max_amount_per_flag_area': 'Well Max Amount Per Flag Area',
    'well_start_decaying_if_flag_area_has_more_than': 'Well Start Decaying If Flag Area Has More Than',
    'turret_max_amount_per_flag_area': 'Turret Max Amount Per Flag Area',
    'turret_start_decaying_if_flag_area_has_more_than': 'Turret Start Decaying If Flag Area Has More Than',
    'garden_max_amount_per_flag_area': 'Garden Max Amount Per Flag Area',
    'allow_floor_placement_on_half_and_low_walls': 'Allow Floor Placement On Half And Low Walls',
    'allow_wall_placement_on_half_and_low_walls': 'Allow Wall Placement On Half And Low Walls',
    'raid_protection_type': 'Raid Protection Type',
    'raid_protection_enable_log': 'Enable Raid Protection Log',
    'raid_protection_flag_specific_change_setting_cooldown': 'Raid Protection Flag Specific Change Setting Cooldown',
    'raid_protection_flag_specific_change_setting_price': 'Raid Protection Flag Specific Change Setting Price',
    'raid_protection_flag_specific_max_protection_time': 'Raid Protection Flag Specific Max Protection Time',
    'raid_protection_offline_protection_start_delay': 'Raid Protection Offline Protection Start Delay',
    'raid_protection_offline_max_protection_time': 'Raid Protection Offline Max Protection Time',
    'raid_protection_global_should_show_raid_times_message': 'Show Raid Times Message',
    'raid_protection_global_should_show_raid_announcement_message': 'Show Raid Announcement Message',
    'raid_protection_global_should_show_raid_start_end_messages': 'Show Raid Start/End Messages',
    'water_price_per_unit_multiplier': 'Water Price Per Unit Multiplier',
    'water_periodic_initial_amount_multiplier': 'Water Periodic Initial Amount Multiplier',
    'water_periodic_max_amount_multiplier': 'Water Periodic Max Amount Multiplier',
    'water_periodic_replenish_amount_multiplier': 'Water Periodic Replenish Amount Multiplier',
    'water_periodic_replenish_interval_multiplier': 'Water Periodic Replenish Interval Multiplier',
    'water_proximity_replenish_amount_multiplier': 'Water Proximity Replenish Amount Multiplier',
    'water_proximity_replenish_chance_multiplier': 'Water Proximity Replenish Chance Multiplier',
    'water_proximity_replenish_timeout_multiplier': 'Water Proximity Replenish Timeout Multiplier',
    'gasoline_price_per_unit_multiplier': 'Gasoline Price Per Unit Multiplier',
    'gasoline_periodic_initial_amount_multiplier': 'Gasoline Periodic Initial Amount Multiplier',
    'gasoline_periodic_max_amount_multiplier': 'Gasoline Periodic Max Amount Multiplier',
    'gasoline_periodic_replenish_amount_multiplier': 'Gasoline Periodic Replenish Amount Multiplier',
    'gasoline_periodic_replenish_interval_multiplier': 'Gasoline Periodic Replenish Interval Multiplier',
    'gasoline_proximity_replenish_amount_multiplier': 'Gasoline Proximity Replenish Amount Multiplier',
    'gasoline_proximity_replenish_chance_multiplier': 'Gasoline Proximity Replenish Chance Multiplier',
    'gasoline_proximity_replenish_timeout_multiplier': 'Gasoline Proximity Replenish Timeout Multiplier',
    'custom_map_enabled': 'Custom Map Enabled',
    'door_lockability.garage': 'Garage Door Lockability',
    'encounter_never_respawn_characters': 'Encounters Never Respawn Characters',
    'abandoned_bunker_reset_armory_lockers_on_activation_only': 'Reset Armory Lockers On Activation Only'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt-BR');

  // Carregar idioma salvo no localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'pt-BR' || savedLanguage === 'en-US')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Função de tradução
  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  // Função para mudar idioma
  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}; 