name: Discord Notifications 
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
 
jobs: 
  notify: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Notify Discord on Push 
        if: github.event_name == 'push' 
        uses: sarisia/actions-status-discord@v1 
        with: 
          webhook: ${{ secrets.DISCORD_WEBHOOK }} 
          status: ${{ job.status }} 
          title: "?? Novo Commit - SCUM Server Manager" 
          description: "**Commit:** ${{ github.event.head_commit.message }}\n**Autor:** ${{ github.event.head_commit.author.name }}\n**Branch:** ${{ github.ref_name }}" 
          color: "0x00ff00" 
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
 
jobs: 
  notify: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Notify Discord on Push 
        if: github.event_name == 'push' 
        uses: sarisia/actions-status-discord@v1 
        with: 
          webhook: ${{ secrets.DISCORD_WEBHOOK }} 
          status: ${{ job.status }} 
          title: "?? Novo Commit - SCUM Server Manager" 
          description: "**Commit:** ${{ github.event.head_commit.message }}\n**Autor:** ${{ github.event.head_commit.author.name }}\n**Branch:** ${{ github.ref_name }}" 
          color: "0x00ff00" 
